name = "mujoco-fort"
version = "0.1.0"
license = "MIT"
author = "Gennadiy Rishkin"
maintainer = "gennadiy.rishkin@gmail.com"
copyright = "Copyright 2022, Gennadiy rishkin"

[build]
link=["mujoco", "GL", "GLEW", "glfw", "m"]


auto-executables = false #true

auto-tests = true
auto-examples = true

[install]
library = false

[[ executable ]]
name="basis"
source-dir="app"
main="basis.f90"

# [[ executable ]]
# name="test_mujoco"
# source-dir="app"
# main="main_mujoco_test.f90"

# [[ executable ]]
# name="test_speed"
# source-dir="app"
# main="main_test_speed.f90"
